default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: debug-statements

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.260
  hooks:
  - id: ruff

# - repo: https://github.com/compilerla/conventional-pre-commit
#   rev: v2.1.1
#   hooks:
#     - id: conventional-pre-commit
#       stages: [commit-msg]
#       args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
  hooks:
    - id: commitizen
      stages: [commit-msg]

# - repo: https://github.com/FalconSocial/pre-commit-mirrors-pep257
#   rev: v0.3.3
#   hooks:
#     - id: pep257

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.4.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
  - id: detect-secrets
    stages: [pre-push]
