version: 1
groups:
    - annotation: {{ cookiecutter.project_shortname }} configuration
      options:

          - key: ckanext.{{ cookiecutter.project_shortname }}.option.name
            default: 10
            type: int
            description: |
                Integer placerat tristique nisl.

          - key: ckanext.{{ cookiecutter.project_shortname }}.multivalued.option
            type: list
            editable: true
            description: |
                Another option that will be parsed as a list of words.
