[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"
tag_format = "v$version"
version_files = ["setup.cfg:version", "setup.py:version"]
major_version_zero = true
changelog_incremental = true
